pipeline {
    agent any

    stages {

        stage('Clonar o repositório') {
            steps {
                git 'https://github.com/GabrielPauloMai/TCC-EBAC' 
            }
        }
        
        stage('Instalar dependências') {
            steps {
                sh 'npm install'
            }
        }
 
        stage('Executar testes') {
            steps {
                sh 'npx run test'
            }
        }
    }
}
